# Для капчи нужен отдельный сервер, это будет работать вот так: Прокси > Капча > Лобби/Ваш основной сервер
# Так что сделайте так, чтобы с прокси человека коннектило к капча серверу, оттуда уже будет на основной или же лобби
#
# И короче lovemetal это сделал, пишите в дискорд если найдёте ошибки: verylovemetal

settings:
  server-after-captcha: "lobby" # Название сервера, на который перекинет игрока после капчи
  session-time: 30 # Время сессии игрока в минутах, чтобы он не выполнял каждый раз капчу
  captcha-time: 120 # Сколько времени будет выделено игроку на капчу
  spawn-point: # Где появиться игрок при заходе
    world: "world"
    x-coord: 9
    y-coord: -59
    z-coord: 12
  players-without-captcha:
    enable: false # Включить ли функцию, чтобы игроки с никами ниже не обязаны были проходить капчу
    nick-names: # Ники игроков, которым не нужно проходить капчу
      - "PLAYER_WITHOUT_CAPTCHA"

proxy:
  period-of-update: 3600 # Раз во сколько обновлять прокси, в секундах (Можете добавить или убрать url и ещё обновить внутри самого url, всё обновиться)
  enable: false # Проверять ли запрещённые пркоси
  url: # Здесь вы можете указать прокси, по ссылке, которые будут заблокированы для захода
    - 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt'
    - 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt'
    - 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt'
    - 'https://api.openproxylist.xyz/socks5.txt'
    - 'https://api.openproxylist.xyz/socks4.txt'
    - 'https://api.openproxylist.xyz/http.txt'
    - 'https://tcpshield.com/blocklist.txt'
    - 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt'
    - 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt'
    - 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt'
    - 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt'

tab-scoreboard: # Настройки таба
  header:
    - "Вы находитесь в капче!"
  footer:
    - "Пройдите её, чтобы перейти на основной сервер"

boss-bar-settings:
  title: "&fВыполните задание: &a%task% &7(%amount%/%amount-to-complete%)"

messages:
  blocked-ip-join: "Ваш IP был запрещён, попробуйте перезагрузить роутер или же попросите помощи у администратора!"
  complete-captcha: "Вы выполнили капчу"
  player-connect-message: "Здравствуйте! Выполните задание, чтобы зайти на основной сервер: %task%"
  kick-message: "Вы не успели пройти капчу!"

# типы капчи: CRAFT_ITEM, BREAK_BLOCK, ENCHANT_ITEM, REMOVE_ENCHANT
tasks: # Тут задачи, которые выпадают на рандом игрок. Вы можете добавлять сколько угодно их
  task-craft:
    type: "CRAFT_ITEM" # Тип капчи, что нужно сделать для прохождения её
    result-item: "STICK" # Что должно получиться после крафта, чтобы выполнить екапчу
    amount-to-complete: 16 # Сколько предметов нужно скрафтить, чтобы выполнить капчу
    task-name: "Скрафтите 16 палок"
    items-to-give: # Тут можно указать, что выдать игроку при заходе, как заполнять: "Тип_Предмета:Количество:Зачарование" Обязателен только Тип_Предмета, остальное опционально
      - "OAK_PLANKS:64"
    boss-bar-color: "RED" # Цвет босс бара
  task-break-block-1:
    type: "BREAK_BLOCK"
    block-type: "OAK_LOG" # Тип блока, который нужно сломать, чтобы выполнить капчу
    amount-to-complete: 4
    task-name: "Сломайте 4 дубовых бревна"
    boss-bar-color: "YELLOW"
  task-break-block-2:
    type: "BREAK_BLOCK"
    block-type: "COAL_ORE"
    amount-to-complete: 3
    task-name: "Добудьте 3 угля"
    boss-bar-color: "YELLOW"
  task-break-block-3:
    type: "BREAK_BLOCK"
    block-type: "DIAMOND_ORE"
    amount-to-complete: 5
    task-name: "Добудьте 5 алмазов"
    boss-bar-color: "YELLOW"
  task-enchant-item:
    type: "ENCHANT_ITEM"
    amount-to-complete: 1
    task-name: "Зачаруйте предмет 1 раз"
    items-to-give:
      - "EXPERIENCE:100" # Можно указать вместо предмета EXPERIENCE и через : указать уровень, который выдать
      - "LAPIS_LAZULI:64"
      - "DIAMOND_AXE"
    boss-bar-color: "GREEN"
  task-remove-enchant:
    type: "REMOVE_ENCHANT"
    amount-to-complete: 1
    task-name: "Снимите зачарование с предмета 1 раз"
    items-to-give:
      - "DIAMOND_AXE:1:EFFICIENCY"
    boss-bar-color: "GREEN"
